services:
  - type: web
    name: infraestructura-peru
    env: docker
    
    # Usar Dockerfile para el build
    dockerfilePath: ./Dockerfile
    
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://admin_render:admin@infraestructura-peru.gl5oqfk.mongodb.net/?retryWrites=true&w=majority&appName=infraestructura-peru
      - key: MONGODB_DATABASE
        value: proyecto_infraestructura
      - key: ENVIRONMENT
        value: production
      - key: GOOGLE_CLIENT_ID
        value: 291287056726-kkh5m8veai6oml865pov2t1s9rblg9g2.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: GOOGLE_REDIRECT_URI
        value: https://infraestructura-peru.onrender.com/google_login.php
        
    # Configuración del plan (gratuito)
    plan: free
    
    # Región (cambia según tu ubicación)
    region: oregon
    
    # Puerto por defecto para Apache
    port: 80
    
    # Dominio personalizado (opcional)
    # customDomains:
    #   - infraestructura-peru.onrender.com