services:
  - type: web
    name: infraestructura-peru
    env: docker
    
    # Usar Dockerfile para el build
    dockerfilePath: ./Dockerfile
    
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://admin_render:admin@infraestructura-peru.gl5oqfk.mongodb.net/?retryWrites=true&w=majority&appName=infraestructura-peru
      - key: MONGODB_DATABASE
        value: proyecto_infraestructura
      - key: ENVIRONMENT
        value: production
        
    # Configuración del plan (gratuito)
    plan: free
    
    # Región (cambia según tu ubicación)
    region: oregon
    
    # Puerto por defecto para Apache
    port: 80
    
    # Dominio personalizado (opcional)
    # customDomains:
    #   - infraestructura-peru.onrender.com